set(SOURCES
    SOURCE/BufferProcessingManager.cpp
    SOURCE/BufferProcessingManager.h
    SOURCE/FileProcessingManager.cpp
    SOURCE/FileProcessingManager.h
    SOURCE/PluginEditor.cpp
    SOURCE/PluginEditor.h
    SOURCE/PluginProcessor.cpp
    SOURCE/PluginProcessor.h
    SOURCE/TD-PSOLA/GrainExport.h
    SOURCE/TD-PSOLA/TD_PSOLA.cpp
    SOURCE/TD-PSOLA/TD_PSOLA.h
    SOURCE/Util/FileUtils.cpp
    SOURCE/Util/FileUtils.h
    SOURCE/Util/Juce_Header.h
    SOURCE/Util/Version.h
    SUBMODULES/RD/SOURCE/AudioFileHelpers.h
    SUBMODULES/RD/SOURCE/AudioFileProcessor.cpp
    SUBMODULES/RD/SOURCE/AudioFileProcessor.h
    SUBMODULES/RD/SOURCE/BufferFiller.h
    SUBMODULES/RD/SOURCE/BufferHelper.h
    SUBMODULES/RD/SOURCE/BufferMath.h
    SUBMODULES/RD/SOURCE/BufferRange.h
    SUBMODULES/RD/SOURCE/BufferWriter.h
    SUBMODULES/RD/SOURCE/CircularBuffer.cpp
    SUBMODULES/RD/SOURCE/CircularBuffer.h
    SUBMODULES/RD/SOURCE/Interpolator.h
    SUBMODULES/RD/SOURCE/PITCH/PitchDetector.cpp
    SUBMODULES/RD/SOURCE/PITCH/PitchDetector.h
    SUBMODULES/RD/SOURCE/PITCH/PitchManager.cpp
    SUBMODULES/RD/SOURCE/PITCH/PitchManager.h
    SUBMODULES/RD/SOURCE/PITCH/PitchMarker.cpp
    SUBMODULES/RD/SOURCE/PITCH/PitchMarker.h
    SUBMODULES/RD/SOURCE/PITCH/TD_PitchDetector.cpp
    SUBMODULES/RD/SOURCE/PITCH/TD_PitchDetector.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GAIN/GainProcessor.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GAIN/GainProcessor.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/Grain.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/Grain.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/Granulator.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/Granulator.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/GranulatorProcessor.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/GranulatorProcessor.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/PitchMarkBuffer.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/PitchMarkHistory.h
    SUBMODULES/RD/SOURCE/RelativeFilePath.h
    SUBMODULES/RD/SOURCE/Util/DebugLog.h
    SUBMODULES/RD/SOURCE/Util/DebugLogger.cpp
    SUBMODULES/RD/SOURCE/Util/DebugLogger.h
    SUBMODULES/RD/SOURCE/Window.cpp
    SUBMODULES/RD/SOURCE/Window.h
)