set(SOURCES
    SOURCE/Audio/AudioFileProcessor.cpp
    SOURCE/Audio/AudioFileProcessor.h
    SOURCE/PluginEditor.cpp
    SOURCE/PluginEditor.h
    SOURCE/PluginProcessor.cpp
    SOURCE/PluginProcessor.h
    SOURCE/Util/FileUtils.cpp
    SOURCE/Util/FileUtils.h
    SOURCE/Util/Juce_Header.h
    SOURCE/Util/Version.h
    SUBMODULES/RD/SOURCE/AudioFileHelpers.h
    SUBMODULES/RD/SOURCE/AudioFileProcessor.cpp
    SUBMODULES/RD/SOURCE/AudioFileProcessor.h
    SUBMODULES/RD/SOURCE/BufferFiller.h
    SUBMODULES/RD/SOURCE/BufferHelper.h
    SUBMODULES/RD/SOURCE/BufferMath.h
    SUBMODULES/RD/SOURCE/BufferRange.h
    SUBMODULES/RD/SOURCE/BufferWriter.h
    SUBMODULES/RD/SOURCE/CircularBuffer.cpp
    SUBMODULES/RD/SOURCE/CircularBuffer.h
    SUBMODULES/RD/SOURCE/Interpolator.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GAIN/GainProcessor.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GAIN/GainProcessor.h
    SUBMODULES/RD/SOURCE/RelativeFilePath.h
    SUBMODULES/RD/SOURCE/Window.cpp
    SUBMODULES/RD/SOURCE/Window.h
)