set(SOURCES
    SOURCE/Components/PluginEditor.cpp
    SOURCE/Components/PluginEditor.h
    SOURCE/Processor/BufferProcessingManager.cpp
    SOURCE/Processor/BufferProcessingManager.h
    SOURCE/Processor/FileToBufferManager.cpp
    SOURCE/Processor/FileToBufferManager.h
    SOURCE/Processor/PluginProcessor.cpp
    SOURCE/Processor/PluginProcessor.h
    SOURCE/TD_PSOLA/GrainExport.h
    SOURCE/TD_PSOLA/TD_PSOLA.cpp
    SOURCE/TD_PSOLA/TD_PSOLA.h
    SOURCE/Util/FileUtils.cpp
    SOURCE/Util/FileUtils.h
    SOURCE/Util/Juce_Header.h
    SOURCE/Util/Version.h
    SUBMODULES/RD/SOURCE/AudioFileHelpers.h
    SUBMODULES/RD/SOURCE/BlockAccumulator.cpp
    SUBMODULES/RD/SOURCE/BlockAccumulator.h
    SUBMODULES/RD/SOURCE/BufferFiller.h
    SUBMODULES/RD/SOURCE/BufferHelper.h
    SUBMODULES/RD/SOURCE/BufferMath.h
    SUBMODULES/RD/SOURCE/BufferRange.h
    SUBMODULES/RD/SOURCE/BufferWriter.h
    SUBMODULES/RD/SOURCE/CircularBuffer.cpp
    SUBMODULES/RD/SOURCE/CircularBuffer.h
    SUBMODULES/RD/SOURCE/DATA_LOGGER/DataLogger.cpp
    SUBMODULES/RD/SOURCE/DATA_LOGGER/DataLogger.h
    SUBMODULES/RD/SOURCE/EDITORS/GainEditor.cpp
    SUBMODULES/RD/SOURCE/EDITORS/GainEditor.h
    SUBMODULES/RD/SOURCE/EDITORS/GrainShifterEditor.cpp
    SUBMODULES/RD/SOURCE/EDITORS/GrainShifterEditor.h
    SUBMODULES/RD/SOURCE/EDITORS/RD_ProcessorSwapperEditor.cpp
    SUBMODULES/RD/SOURCE/EDITORS/RD_ProcessorSwapperEditor.h
    SUBMODULES/RD/SOURCE/FX/Fade.cpp
    SUBMODULES/RD/SOURCE/FX/Fade.h
    SUBMODULES/RD/SOURCE/Interpolator.h
    SUBMODULES/RD/SOURCE/MarkWriter.cpp
    SUBMODULES/RD/SOURCE/MarkWriter.h
    SUBMODULES/RD/SOURCE/PITCH/FFT_PitchDetector.cpp
    SUBMODULES/RD/SOURCE/PITCH/FFT_PitchDetector.h
    SUBMODULES/RD/SOURCE/PITCH/PitchManager.cpp
    SUBMODULES/RD/SOURCE/PITCH/PitchManager.h
    SUBMODULES/RD/SOURCE/PITCH/PitchMark.h
    SUBMODULES/RD/SOURCE/PITCH/PitchMarker.cpp
    SUBMODULES/RD/SOURCE/PITCH/PitchMarker.h
    SUBMODULES/RD/SOURCE/PITCH/SynthMark.cpp
    SUBMODULES/RD/SOURCE/PITCH/SynthMark.h
    SUBMODULES/RD/SOURCE/PITCH/SynthMarker.cpp
    SUBMODULES/RD/SOURCE/PITCH/SynthMarker.h
    SUBMODULES/RD/SOURCE/PITCH/YIN_PitchDetector.cpp
    SUBMODULES/RD/SOURCE/PITCH/YIN_PitchDetector.h
    SUBMODULES/RD/SOURCE/PROCESSORS/BASE/RD_Processor.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/BASE/RD_Processor.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GAIN/GainProcessor.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GAIN/GainProcessor.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/Grain.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/GrainShifterProcessor.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/GrainShifterProcessor.h
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/Granulator.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/GRAIN/Granulator.h
    SUBMODULES/RD/SOURCE/PROCESSORS/RD_ProcessorSwapper.cpp
    SUBMODULES/RD/SOURCE/PROCESSORS/RD_ProcessorSwapper.h
    SUBMODULES/RD/SOURCE/RelativeFilePath.h
    SUBMODULES/RD/SOURCE/Util/DebugLog.h
    SUBMODULES/RD/SOURCE/Util/DebugLogger.cpp
    SUBMODULES/RD/SOURCE/Util/DebugLogger.h
    SUBMODULES/RD/SOURCE/Util/Juce_Header.h
    SUBMODULES/RD/SOURCE/Util/Version.h
    SUBMODULES/RD/SOURCE/Window.cpp
    SUBMODULES/RD/SOURCE/Window.h
)